# Assignment 1
1. Generate an np array of (a) vector of lenght 50 (b) two dimension of shape 5x4. Both uniformly distributed between 0 and 1
2. Split the two dimension array in 1 above into three arrays taking the first two rows, follow by the next two rows and put the remaining row in another variable
3. Split the vector into in 1 above three arrays by taking the first 15, follow by the next 20 and the remaining into another variable.
4. Create a 4x5 array: 
   (a). Using manual method
   (b). Using randomly generated value between 0 and 1
   (c). Using array of ones

In [46]:
import numpy as np

In [66]:
#1. Generate an np array of (a) vector of lenght 50 (b) two dimension of shape 5x4.
#Both uniformly distributed between 0 and 1
vt=np.random.random(50)
vt

array([0.8742349 , 0.49117047, 0.71610729, 0.90403393, 0.6809621 ,
       0.1724151 , 0.47086525, 0.04089779, 0.5208141 , 0.15153191,
       0.71154567, 0.7700456 , 0.73277518, 0.34745988, 0.7119036 ,
       0.57649281, 0.27365067, 0.46083004, 0.35728644, 0.88309174,
       0.31151471, 0.7957097 , 0.11820711, 0.64470254, 0.46981948,
       0.61385084, 0.77392926, 0.33863165, 0.56014869, 0.19939825,
       0.62668957, 0.11915087, 0.44795683, 0.79131522, 0.43034284,
       0.27450142, 0.04903878, 0.85790271, 0.97206353, 0.59580247,
       0.01322819, 0.77849336, 0.60286648, 0.37856243, 0.9176115 ,
       0.20865598, 0.13256418, 0.41693256, 0.8159664 , 0.34617623])

In [67]:
#b. Split the two dimension array in 1 above into three arrays taking the first two rows,
#follow by the next two rows and put the remaining row in another variable
np.random.seed(0)
vtr=np.random.random((5,4))
vtr

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675, 0.87001215]])

In [4]:
#2. Split the two dimension array in 1 above into three arrays taking the first two rows, follow
#by the next two rows and put the remaining row in another variable
first, second, third = np.vsplit(vtr,[2,4])
print("the first split\n",first)
print("the second split\n",second)
print("the third split\n",third)

the first split
 [[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]]
the second split
 [[0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]
the third split
 [[0.0202184  0.83261985 0.77815675 0.87001215]]


In [6]:
#3. Split the vector into in 1 above three arrays by taking the first 15, follow by the next 20
#and the remaining into another variable.
x1,x2,x3 = np.split(vt,(15,35))
print(x1,x2,x3)

[0.49683542 0.80777561 0.71049224 0.40710565 0.78297408 0.85935318
 0.43453697 0.60419488 0.62691234 0.19412915 0.19716775 0.56591901
 0.69926397 0.0720287  0.2779893 ] [0.99211955 0.66856063 0.15916415 0.60599983 0.40540394 0.3638743
 0.80549499 0.7936431  0.53420858 0.61882164 0.62657412 0.24833743
 0.96014864 0.47980446 0.86225469 0.27198282 0.00673704 0.89551179
 0.69796259 0.40457352] [0.87152786 0.7448211  0.72521458 0.60090569 0.50282957 0.36440695
 0.43646836 0.47763168 0.51875694 0.22163512 0.62489085 0.360497
 0.60075648 0.14783433 0.19595356]


In [7]:
#4. Create a 4x5 array: (a). Using manual method (b). Using randomly generated
# value between 0 and 1 (c). Using array of ones

np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
# (b). Using randomly generated value between 0 and 1
np.random.random((4,5))

array([[0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443],
       [0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ]])

In [9]:
# (c). Using array of ones
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Assignment 2:
#use us_births data to compute the following using np:
    #extract the year, gender and births column from the data
    #compute the aggregation of sum of total birth, sum of female birth and sum of male birth, mean and median
    #compute the maximum births and minimum births
    #indicate the gender with minimum birth and maximum birth
    #indicate the year with minimum birth and maximum birth

In [69]:
# import numpy to start using numpy package
import numpy as np

In [1]:
import pandas as pd
us_births = pd.read_csv('C:\\Datasets\\us_births.csv')
us_births.head()

year  month  day gender  births
0  1969      1  1.0      F    4046
1  1969      1  1.0      M    4440
2  1969      1  2.0      F    4454
3  1969      1  2.0      M    4548
4  1969      1  3.0      F    4548

In [71]:
# extract the year, gender and births column from the data
us_year = np.array(us_births['year'])
#gender = us_birth.gender.values
us_gender = np.array(us_births['gender'])
#birth = us_birth['birth'].values
us_birth = np.array(us_births['births'])
print("Us Year\n",us_year,"\n")
print("Us Gender\n",us_gender,"\n")
print("Us Births\n",us_birth,"\n")

Us Year
 [1969 1969 1969 ... 2008 2008 2008] 

Us Gender
 ['F' 'M' 'F' ... 'M' 'F' 'M'] 

Us Births
 [  4046   4440   4454 ... 165468 173215 181235] 



In [120]:
#compute the aggregation of sum of total birth, sum of female birth and sum of male birth, mean 
#and standard deviation
#print("sum of total birth: ", np.sum(birth))
print("sum of total birth: ", us_birth.sum())
print("sum of female birth: ", np.sum(us_birth[np.equal(us_gender,"F")])) 
# print("sum of male birth: ", us_gender.sum(<M))
print("sum of male birth: ", np.sum(us_birth[np.equal(us_gender,"M")]))
print("mean birth:   ", us_birth.mean())
print("median birth:", np.median(us_birth))
print("standard deviation of total birth:", np.std(us_birth))

sum of total birth:  151774378
sum of female birth:  74035823
sum of male birth:  77738555
mean birth:    9762.293561458802
median birth: 4814.0
standard deviation of total birth: 28551.547532287397


In [61]:
#compute the maximum births and minimum births
print("maximum birth: ", us_birth.max())
print("minimum birth: ", us_birth.min())

maximum birth:  199622
minimum birth:  1


In [84]:
#indicate the gender with minimum birth and maximum birth
print("Gender with Minimum birth: ", us_gender[np.argmin(us_birth)])
print("Gender with Maximum birth: ", us_gender[np.argmax(us_birth)])

Gender with Minimum birth:  F
Gender with Maximum birth:  M


In [85]:
 #indicate the year with minimum birth and maximum birth
print("Year with Minimum birth: ", us_year[np.argmin(us_birth)])
print("Year with Maximum birth: ", us_year[np.argmax(us_birth)])

Year with Minimum birth:  1975
Year with Maximum birth:  2007


#  Assignment 3
Using the Bicycle Weather.csv dataset perform the following operations: 1. Extract the PRCP column from the pandas object. 2. Using boolean functions/operators separate numbers from NAN 3. Using boolean masking separate all zeros and non-zeros into different variables. 4. From the variable holding non-zeros, multiply every values in the array with 100 and divid by 250 5. Calculate the following: a. Median precip on rainy days b. Median precip on summer days c. Maximum precip on summer days d. Median precip on non-summer rainy days

In [7]:
import numpy as np
import pandas as pd
seattle = pd.read_csv('C:\\Datasets\\BicycleWeather.csv')
seattle.head()

STATION                                STATION_NAME      DATE  \
0  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120101   
1  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120102   
2  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120103   
3  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120104   
4  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120105   

   PRCP  SNWD  SNOW  TMAX  TMIN  AWND  WDF2  ...  WT17  WT05  WT02  WT22  \
0     0     0     0   128    50    47   100  ... -9999 -9999 -9999 -9999   
1   109     0     0   106    28    45   180  ... -9999 -9999 -9999 -9999   
2     8     0     0   117    72    23   180  ... -9999 -9999 -9999 -9999   
3   203     0     0   122    56    47   180  ... -9999 -9999 -9999 -9999   
4    13     0     0    89    28    61   200  ... -9999 -9999 -9999 -9999   

   WT04  WT13  WT16  WT08  WT18  WT03  
0 -9999 -9999 -9999 -9999 -9999 -9999  
1 -9999     1     1 -9999 -9999 -9999  
2 -9999 -9999     1 -9999 -9999 -9999  
3 -9999     1     1 -9999 -9999 -9999  
4 -9999 -9999     1 -9999 -9999 -9999  

[5 rows x 26 columns]

In [5]:
#1. Extract the PRCP column from the pandas object.
# prcp = seattle['PRCP'].values
# prcp
prcp = seattle["PRCP"].values
print(prcp)
print(prcp.size)

[  0 109   8 ... 102   0  58]
1340


In [141]:
#2. Using boolean functions/operators separate numbers from NAN
np.greater_equal(prcp, 0)

array([ True,  True,  True, ...,  True,  True,  True])

In [140]:
3. #Using boolean masking separate all zeros into different variables.
zero = prcp[np.equal(prcp,0)]
non_zero = prcp[np.greater(prcp,0)]
print("zero values: ", zero)
print("non_zero values: ", non_zero)

zero values:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 

In [112]:
#non-zeros into different variables.
inche =inches[val]
non_rainy = (inches == 0)
inches[non_rainy]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [116]:
#4. From the variable holding non-zeros, multiply every values in the array with 100 and divid by 250
(non_zero * 100)/250

array([ 43.6,   3.2,  81.2,   5.2,  10. ,  17.2,   4. ,  16.4,  21.2,
        10. ,  32.4,  79.2,  60.8,  54. ,  12. ,  24.4,  34.4,  32.4,
        19.2, 110.8,  14.4,   7.2,  54. ,   1.2,  11.2,  10. ,  10. ,
         3.2,   4. ,  45.6,  10. ,   7.2,  69.2,  25.6,  12. ,   3.2,
        34.4,  45.6,   5.2,  14.4,   3.2,   8. ,  27.6,   2. ,  14.4,
        41.6,  54.8,  77.2,  37.6,  34.4,  95.6,  33.6,  37.6,  14.4,
         8. ,  14.4,   5.2,  16.4,  19.2,   5.2, 109.6,  22.4,  52.8,
         6. ,   6. ,  18.4,   1.2,   9.2,   2. ,  32.4,   7.2,   7.2,
        43.6,  26.4,  17.2,  42.8,  15.2,   3.2,  17.2,  17.2,   2. ,
         2. ,  74. ,   7.2,  25.6,  56. ,  24.4,   1.2,   1.2,  15.2,
        26.4,   1.2,   5.2,  64. ,  66. ,   6. ,   3.2,  12. ,   4. ,
        62.8,  34.4,   2. ,   1.2,  12. ,   8. ,  23.2,   6. ,   2. ,
         1.2,  60.8,   4. ,   1.2,   1.2,   1.2,   8. ,  19.2,  66. ,
        31.6,  83.2,  19.2,   2. ,  25.6,  35.6,  28.4,   6. ,  92.4,
        24.4,  43.6,

In [126]:
# 5. Calculate the following: a. Median precip on rainy days b. Median precip on
#summer days c. Maximum precip on summer days d. Median precip on non-summer rainy days
print("Median precip on rainy days in 2012 (inches): ", np.median(non_zero))

Median precip on rainy days in 2012 (inches):  38.0


In [133]:
#b. Median precip on summer days
#556/2=278
summer = (np.arange(556)-278<90) & (np.arange(556)-278>0)
summer_prcp = non_zero[summer]
print("median precip of summer days: ", np.median(summer_prcp))

median precip of summer days:  36.0


In [136]:
#c. Maximum precip on summer days d. Median precip on non-summer rainy day
print("maximum precip of summer days: ", np.max(summer_prcp))

maximum precip of summer days:  467


In [139]:
#d. Median precip on non-summer rainy day
print("median precip of non_summer days: ", np.median(non_zero[~summer]))

median precip of non_summer days:  38.0
